### ISSUE TITLE
Error when running SpatialFeaturePlotBlend

### ISSUE THREAD

**Issue by QuinceyLv** [george-hall-ucl/SpatialFeaturePlotBlend#5] opened 2024-09-03 06:50 UTC
Hi, 

I ran into a weird bug when using SpatialFeaturePlotBlend at https://github.com/george-hall-ucl/SpatialFeaturePlotBlend/blob/342949d8b13e085095d71ec57556bbf8abec87d2/SpatialFeaturePlotBlend.R#L66:

Error in `[.data.frame`(GetTissueCoordinates(object = object[[x]]), cells,  : 
  undefined columns selected

And then I checked my object:

![image](https://github.com/user-attachments/assets/5af59ed9-cdab-4c34-ae85-1b53092c28bc)

I could subset the object using any other columns but not 'image_id'.

So I renamed the column and it worked. Maybe there are some name conflicts?

![image](https://github.com/user-attachments/assets/536a63ab-b13e-4bf0-bcba-26ec530699a5)

**Comment by george-hall-ucl** [comment] 2024-09-03 09:47
Hi,

Thank you for bringing this to my attention and for doing some investigations! I agree, this is a weird bug since it can be solved by renaming a column...

I think it might be being caused by my slightly dodgy handling of multiple images. Do you have mutltiple images in your Seurat object? In any case, I think the multiple image handling code might have been the cause, so I've re-implemented the relevant bit of the function now. You can find it in the `multiple_images_bugfix` branch [here](https://github.com/george-hall-ucl/SpatialFeaturePlotBlend/blob/multiple_images_bugfix/SpatialFeaturePlotBlend.R). Does this new version work for you?

If this still doesn't work, please let me know and I can investigate further! (let me know the structure of your dataset and your version of Seurat)


Thanks,
George

**Comment by george-hall-ucl** [comment] 2024-12-13 11:23
Hi,

I've now pushed this fix into the main branch and will close this issue. Please let me know if it doesn't work for you!

Thanks,
George

**Closed as completed by george-hall-ucl** 2024-12-13 11:23 UTC
